### ISSUE TITLE
Overall Title/Tag Overlap

### ISSUE THREAD

**Issue by sawprogramming** [sawprogramming/youtube_tag_analysis#17]
Show the percentage of words in the title that were also tags (different from #15) for each video.

Issues #15, #16, #17, #18, #19, and #20 will all be displayed in the same table.

**Comment by sawprogramming** [comment]
Implemented.

![Basic Overlap Table](http://i.imgur.com/DphQCjl.png)

**Comment by parraro** [comment]
Are you splitting words and removing special characters before computing the overlap?

For instance, if a tag has the value "Java (programming language)" are you separating it into the three words Java, programming, language before computing overlap?

**Comment by sawprogramming** [comment]
I split and filtered the title and the description but left the tags as is. Once I "finished" the project, I was going to go ask you all how you wanted that handled. There's a lot of special cases with CS terms like "!=" that would/are getting erased by removing special characters.

**Comment by parraro** [comment]
It is ok if CS terms such as "!=" are removed as they are generally not descriptive enough. 
I think the best way to handle special characters removal and title/description/tag splitting is to have a set of configuration flags (i.e., SPECIAL and SPLIT) to determine how to handled those.
SPECIAL: When this flag is set to TRUE, special characters are removed. When the flag is set to false no special characters are removed.
SPLIT: When this flag is set to TRUE tags are split . When this flag is set to FALSE tags are left as is.
Splitting should be done on spaces, underscores, and Uppercase convention.
Splitting examples: 
"clearField" -> clear field
"clear field" -> clear field
"clear_field" -> clear field
